### ISSUE TITLE
LICENSE missing

### ISSUE THREAD

**Issue by shankscoder** [rohanarun/Open-Agent-Studio#22]
Can you please clarify what license you're releasing the source code under and add a LICENSE file to the repo?

Would help with clarifying the use of the software especially in commercial use cases.

Thanks. Great work on the project. Looks amazing.

**Comment by rohanarun** [comment]
Hi thanks this has been updated here: https://github.com/rohanarun/Open-Agent-Studio/blob/master/LICENSE

**Comment by rohanarun** [comment]
https://github.com/rohanarun/Open-Agent-Studio/blob/master/LICENSE
